## This text classification program uses a probabilistic machine learning algorithm, Naive Bayes, to guess whether a What'sApp message is a "consulta" (consulation) or a "reclamo" (complaint).

In [25]:
import pandas as pd
import numpy as np
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from nltk.corpus import stopwords

In [26]:
nltk.download('stopwords')
stop_words = stopwords.words("spanish")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/brandonjanes/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [27]:
#read dataset from csv
df = pd.read_csv('mattermost_etiquetado.csv')

In [28]:
# change type to bianary
df.loc[df["type"]=='consulta',"type"]=0
df.loc[df["type"]=='reclamo',"type"]=1

In [29]:
df_x = df["text"]
df_y = df["type"]

In [30]:
#average of 'reclamos' versus 'consultas'
reclamo_total = df_y.sum()
total = df.type.count()
average = reclamo_total / total
print(average*100,"percent of the messages are 'reclamos'.")

12.177121771217712 percent of the messages are 'reclamos'.


##### WARNING: If the percent of 'reclamos' is very low, this will cloud the accuracy of our classification accuracy calculator. For example, if the 'reclamo' percent is 10 percent, a dumb classifier, which predicts 'consulta' every time, would be 90 percent accurate. 

In [31]:
#split the data (this is a commonly used line of code)
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [10]:
#for TYPE we need our bianary values to be integers
y_train=y_train.astype('int')

### Count Vectorizer

In [11]:
cv = CountVectorizer()

In [12]:
x_traincv=cv.fit_transform(x_train)
x_traincv

<216x611 sparse matrix of type '<class 'numpy.int64'>'
	with 1895 stored elements in Compressed Sparse Row format>

In [13]:
arrai=x_traincv.toarray()
arrai

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### Multinomial Naive Bayes Classifier with Count Vectorizer

In [14]:
# for applying the Naive Bayes algorithm use "fit()" - this is the line where we are training our model
mnb_trained = MultinomialNB().fit(x_traincv, y_train)

In [15]:
# test data use "transform()"
x_testcv = cv.transform(x_test)

In [16]:
#predictions of (0=consulta, 1=reclamo)
pred = mnb_trained.predict(x_testcv)
pred

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [19]:
#original data (0=consulta, 1=reclamo)
actual=np.array(y_test)
actual

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1], dtype=object)

In [20]:
# preparing our results for a tabular visualization
messg = []
for msg in x_test:
    messg.append(msg)
predictions = []
for x in pred:
    predictions.append(x)
original = []
for i in y_test:
    original.append(i)

In [21]:
# this is the Original, hand labeled data
dataf = pd.DataFrame({'ORIGINAL_TYPE' : original,
                      'ML_PREDICT' : predictions,
                     'TEXT' : messg})
dataf

ML_PREDICT  ORIGINAL_TYPE  \
0            0              0   
1            0              0   
2            0              0   
3            0              0   
4            0              0   
5            0              0   
6            1              0   
7            0              0   
8            0              1   
9            0              0   
10           0              0   
11           0              0   
12           0              0   
13           0              0   
14           0              1   
15           0              0   
16           0              0   
17           0              0   
18           0              0   
19           0              0   
20           0              0   
21           0              0   
22           0              0   
23           0              0   
24           0              0   
25           0              0   
26           0              0   
27           0              0   
28           0              1   
29           0              0   
30           0              0   
31           0              0   
32           0              0   
33           1              1   
34           0              0   
35           0              0   
36           0              0   
37           0              1   
38           0              0   
39           0              0   
40           0              0   
41           0              0   
42           0              1   
43           0              0   
44           0              0   
45           0              0   
46           0              0   
47           0              0   
48           0              0   
49           0              0   
50           0              0   
51           0              0   
52           1              1   
53           0              0   
54           1              1   

                                                 TEXT  
0                                        Y en SanCor?  
1                                             gracias  
2         Me podes  confirmar si voy a poderlo hacer?  
3   Quería consultar sobre un seguro de accidente ...  
4   Tengo un auto Ford falcon modelo 1983 y quería...  
5                                    Me llamo Natalia  
6              pense q seria 690 el valor de la cuota  
7   Toco el boton donde dice otros medios de pagos...  
8                             Gente necesitamos ayuda  
9   y asi como yo estoy interviniendo, también pod...  
10              Hola soy un cliente o posible cliente  
11   Yo tenía con ustedes pero se me venció la poliza  
12                        Mandame una foto de tu auto  
13        Me podrían decir cómo hago para cambiar eso  
14  Disculpa la insistencia salgo a las cuatro del...  
15                   Me lo piden de mi seguro x favor  
16                                 pasame una bandera  
17     Necesito que me den el link de pago de mí auto  
18                                        Te consulto  
19          además necesitaría una copia de la poliza  
20  una pregunta sale los datos x q la  caminera t...  
21   Yo tenía con ustedes pero se me venció la poliza  
22  Por favor  necesito pagar la voleta estoy en B...  
23  Necesitó la boleta para poder pagar mi seguro....  
24  Como hacemos te paso los datos o foto de la ta...  
25                         no me estaria respondiendo  
26                                             Genial  
27                                 O sea que me cubre  
28                                  No llegó nada aún  
29                          es lo que me habian dicho  
30  El evento ocurrió el 23, no el 24, como reza l...  
31  perdon, el costo cual seria al final, el que m...  
32  Cuando me decís cuatrimestral es porque aument...  
33                                 Me podes responder  
34         Es saber si podía hacer de nuevo el seguro  
35                             Tranqui chiquita nomas  
36                                      que necesita?  
37  Muy irresponsables.. ho

In [24]:
count=0
for i in range (len(pred)):
    if pred[i]==actual[i]:
        count=count+1
print("We have",count,"correct predictions out of",len(pred),".")
print("That's",(count/len(pred))*100,"accuracy")

We have 49 correct predictions out of 55 .
That's 89.0909090909091 accuracy
